apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: middle-coral-python 
  janus-idp.io/tekton: middle-coral-python
  backstage.io/kubernetes-id: middle-coral-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: middle-coral-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  