apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: middle-coral-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: middle-coral-python 
  name: middle-coral-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: middle-coral-python 
